"""Generate a TradingView Pine Script v5 indicator from the latest cycle's
best strategy.  Runs inside the 5h-cycle workflow after the main sweep.

Reads:  state/cycle_latest.json
Writes: tradingview/auto_best_strategy.pine
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone, timedelta

TZ_UTC5 = timezone(timedelta(hours=5))
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATE = os.path.join(ROOT, "state", "cycle_latest.json")
OUTPUT = os.path.join(ROOT, "tradingview", "auto_best_strategy.pine")


def main() -> None:
    if not os.path.exists(STATE):
        print("[pine] no cycle_latest.json — skip")
        return

    cycle = json.load(open(STATE))
    top3 = cycle.get("top3", [])
    if not top3:
        print("[pine] no top3 — skip")
        return

    now = datetime.now(TZ_UTC5).strftime("%Y-%m-%d %H:%M UTC+5")
    lines: list[str] = []
    lines.append('// @version=5')
    lines.append(f'// Auto-generated by cycle_5h at {now}')
    lines.append(f'// Top-{len(top3)} strategies from latest sweep')
    lines.append('')
    lines.append(f'indicator("FOREX Auto-Strategy [{now}]", overlay=true)')
    lines.append('')

    for i, r in enumerate(top3, 1):
        pair = r.get("pair", "???")
        wr = r.get("wr", 0)
        tpd = r.get("trades_per_day", 0)
        p = r.get("params", {})
        direction = r.get("direction", 0)
        ind = r.get("indicators_now", {})

        lines.append(f'// === {i}. {pair} — WR {wr}% · {tpd:.1f} trades/day ===')

        # Strategy params as Pine inputs
        prefix = f"s{i}"
        lines.append(f'{prefix}_adx_min = input.float({p.get("adx_min", 18)}, "#{i} {pair} ADX min")')
        lines.append(f'{prefix}_adx_max = input.float({p.get("adx_max", 60)}, "#{i} {pair} ADX max")')
        lines.append(f'{prefix}_conf_min = input.int({p.get("min_conf", 72)}, "#{i} {pair} Min Confidence")')
        lines.append(f'{prefix}_tq_min = input.int({p.get("min_trend_q", 65)}, "#{i} {pair} Min Trend Quality")')
        lines.append(f'{prefix}_horizon = input.int({p.get("horizon_bars", 20) * 15}, "#{i} {pair} Horizon (min)")')
        lines.append(f'{prefix}_require_mtf = input.bool({str(p.get("require_mtf", True)).lower()}, "#{i} {pair} Require MTF")')
        lines.append('')

        # Current signal annotation
        side_str = "BUY" if direction == 1 else ("SELL" if direction == -1 else "WAIT")
        conf = ind.get("confidence", 0)
        adx = ind.get("adx", 0)
        lines.append(f'// Current signal: {side_str} (confidence {conf:.0f}%, ADX {adx:.0f})')
        lines.append('')

    # Simple ADX + EMA logic for the first pair
    best = top3[0]
    p = best.get("params", {})
    lines.append('// --- Live Signal Logic (pair #1) ---')
    lines.append(f'adx_len = input.int(14, "ADX Length")')
    lines.append(f'[diPlus, diMinus, adxVal] = ta.dmi(adx_len, adx_len)')
    lines.append(f'ema_fast = ta.ema(close, 8)')
    lines.append(f'ema_slow = ta.ema(close, 21)')
    lines.append('')
    lines.append(f'bull_signal = adxVal >= s1_adx_min and adxVal <= s1_adx_max and ema_fast > ema_slow and diPlus > diMinus')
    lines.append(f'bear_signal = adxVal >= s1_adx_min and adxVal <= s1_adx_max and ema_fast < ema_slow and diMinus > diPlus')
    lines.append('')
    lines.append('plotshape(bull_signal, style=shape.triangleup, location=location.belowbar, color=color.green, size=size.small, title="BUY")')
    lines.append('plotshape(bear_signal, style=shape.triangledown, location=location.abovebar, color=color.red, size=size.small, title="SELL")')
    lines.append('')
    lines.append(f'// WR: {best.get("wr", 0)}% on 365-day backtest')
    lines.append(f'// Trades/day: {best.get("trades_per_day", 0):.1f}')
    lines.append(f'// Pair: {best.get("pair", "?")}')

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[pine] wrote {OUTPUT} ({len(lines)} lines, top {len(top3)} pairs)")


if __name__ == "__main__":
    main()
